language:
  - python
  - cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgmp-dev
python:
  - "2.6"
  - "2.7"
script: "python setup.py build"
install: "pip install -r requirements.txt"
script: nosetests
