before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgmp-dev
language: python
python:
  - "2.6"
  - "2.7"
script: python setup.py build_ext
install: "pip install -r requirements.txt"
script: nosetests
