language:
  - python
  - cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgmp-dev
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "python setup.py build"
script:
  - "python setup.py test"
